import { MigrationInterface, QueryRunner } from "typeorm";

export class AddBookDetails1775747431811 implements MigrationInterface {
    name = 'AddBookDetails1775747431811'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "fk_addresses_user_id_public.users"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "fk_reviews_user_id_public.users"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "fk_reviews_book_id_public.books"`);
        await queryRunner.query(`ALTER TABLE "book_images" DROP CONSTRAINT "fk_book_images_book_id_public.books"`);
        await queryRunner.query(`ALTER TABLE "embeddings" DROP CONSTRAINT "fk_embeddings_book_id_public.books"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "fk_payments_order_id_public.orders"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_user_id_public.users"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_address_id_public.addresses"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_order_id_public.orders"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_book_id_public.books"`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" DROP CONSTRAINT "fk_user_behaviors_user_id_public.users"`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" DROP CONSTRAINT "fk_user_behaviors_book_id_public.books"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "fk_books_category_id_public.categories"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cart_items_cart_id_public.carts"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cart_items_book_id_public.books"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "fk_carts_user_id_public.users"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "fk_refresh_tokens_user_id_public.users"`);
        await queryRunner.query(`ALTER TABLE "user_advances" DROP CONSTRAINT "fk_user_advances_user_id_public.users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_embeddings_vector_cosine"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "translator" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "publisher" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "publish_year" integer`);
        await queryRunner.query(`ALTER TABLE "books" ADD "pages" integer`);
        await queryRunner.query(`ALTER TABLE "books" ADD "dimensions" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "weight" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "format" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "language" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "original_price" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "discount" integer`);
        await queryRunner.query(`ALTER TABLE "books" ADD "highlights" text`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "book_images" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "embeddings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_behaviors_user_id_created_at"`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "carts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_user_id_created_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_advances" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_advances" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_advances" ADD CONSTRAINT "uq_user_advances_user_id" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_user_behaviors_user_id_created_at" ON "user_behaviors" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_user_id_created_at" ON "refresh_tokens" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "fk_addresses_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "fk_reviews_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "fk_reviews_book_id_books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_images" ADD CONSTRAINT "fk_book_images_book_id_books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embeddings" ADD CONSTRAINT "fk_embeddings_book_id_books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_order_id_orders" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_address_id_addresses" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_order_id_orders" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_book_id_books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" ADD CONSTRAINT "fk_user_behaviors_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" ADD CONSTRAINT "fk_user_behaviors_book_id_books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "fk_books_category_id_categories" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_items_cart_id_carts" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_items_book_id_books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "fk_carts_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_advances" ADD CONSTRAINT "fk_user_advances_user_id_users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_advances" DROP CONSTRAINT "fk_user_advances_user_id_users"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "fk_refresh_tokens_user_id_users"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "fk_carts_user_id_users"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cart_items_book_id_books"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cart_items_cart_id_carts"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "fk_books_category_id_categories"`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" DROP CONSTRAINT "fk_user_behaviors_book_id_books"`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" DROP CONSTRAINT "fk_user_behaviors_user_id_users"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_book_id_books"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_order_id_orders"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_address_id_addresses"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_user_id_users"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "fk_payments_order_id_orders"`);
        await queryRunner.query(`ALTER TABLE "embeddings" DROP CONSTRAINT "fk_embeddings_book_id_books"`);
        await queryRunner.query(`ALTER TABLE "book_images" DROP CONSTRAINT "fk_book_images_book_id_books"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "fk_reviews_book_id_books"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "fk_reviews_user_id_users"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "fk_addresses_user_id_users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_user_id_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_behaviors_user_id_created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_advances" DROP CONSTRAINT "uq_user_advances_user_id"`);
        await queryRunner.query(`ALTER TABLE "user_advances" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_advances" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_user_id_created_at" ON "refresh_tokens" ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "carts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "idx_user_behaviors_user_id_created_at" ON "user_behaviors" ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "embeddings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "book_images" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "highlights"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "discount"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "original_price"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "language"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "format"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "weight"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "dimensions"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "pages"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "publish_year"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "publisher"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "translator"`);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_embeddings_vector_cosine" ON "embeddings" ("vector") `);
        await queryRunner.query(`ALTER TABLE "user_advances" ADD CONSTRAINT "fk_user_advances_user_id_public.users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_user_id_public.users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "fk_carts_user_id_public.users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_items_book_id_public.books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cart_items_cart_id_public.carts" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "fk_books_category_id_public.categories" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" ADD CONSTRAINT "fk_user_behaviors_book_id_public.books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_behaviors" ADD CONSTRAINT "fk_user_behaviors_user_id_public.users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_book_id_public.books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_order_id_public.orders" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_address_id_public.addresses" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_user_id_public.users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_order_id_public.orders" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embeddings" ADD CONSTRAINT "fk_embeddings_book_id_public.books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_images" ADD CONSTRAINT "fk_book_images_book_id_public.books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "fk_reviews_book_id_public.books" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "fk_reviews_user_id_public.users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "fk_addresses_user_id_public.users" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
